apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  selector:
    app: grafana
    tier: influxdb
  ports:
    - protocol: TCP
      port: 8086
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
      tier: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: influxdb
    spec:
      containers:
      - image: influxdb
        imagePullPolicy: Never
        name: influxdb
        ports:
        - containerPort: 8086
          name: influxdb
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pv-claim