apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1         #Create 1 pod matching with "template" description (line 26)
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx    #Take nginx image create with dockerfile
        imagePullPolicy: Never  #without this it will look for an image online.
